--drop tables that are auto-generated by the EF tools that I don't actually want
DROP TABLE algorithm_item_info_entity;
DROP TABLE algorithm_video_entity;

--default to open invite
INSERT INTO invite_code (code, remaining_uses, usage_count)
VALUES ('', 1000000, 0);