using Microsoft.EntityFrameworkCore;
using MyVidious.Background;
using MyVidious.Data;
using MyVidious.Models.Admin;
using MyVidious.Utilities;
using Quartz;

namespace MyVidious.Access;

public class AdminAccess
{
    private VideoDbContext _videoDbContext;
    private InvidiousAPIAccess _invidiousApiAccess;
    private MeilisearchAccess _meilisearchAccess;
    private ISchedulerFactory _schedulerFactory;
    private GlobalCache _globalCache;

    public AdminAccess(
        VideoDbContext videoDbContext,
        InvidiousAPIAccess invidiousApiAccess,
        MeilisearchAccess meilisearchAccess,
        ISchedulerFactory schedulerFactory,
        GlobalCache globalCache
        )
    {
        _videoDbContext = videoDbContext;
        _invidiousApiAccess = invidiousApiAccess;
        _meilisearchAccess = meilisearchAccess;
        _schedulerFactory = schedulerFactory;
        _globalCache = globalCache;

    }

    public async Task<IEnumerable<FoundChannel>> SearchChannels(string searchText)
    {
        if (searchText == null || searchText.Length < 2)
        {
            throw new WebRequestException(400, "searchText must be at least length 2");
        }
        var invidiousResults = await _invidiousApiAccess.Search(new Models.Invidious.SearchRequest
        {
            Q = searchText,
            Type = "channel",
        });
        var invidiousChannels = invidiousResults.OfType<Models.Invidious.SearchResponse_Channel>().Take(10).ToList();
        var uniqueIds = invidiousChannels.Select(z => z.AuthorId).ToList();
        if (!uniqueIds.Any())
        {
            return Enumerable.Empty<FoundChannel>();
        }
        var existingChannels = await _videoDbContext.Channels.Where(z => uniqueIds.Contains(z.UniqueId)).ToListAsync();
        var response = invidiousChannels.Select(invidiousChannel =>
        {
            var existingChannel = existingChannels.FirstOrDefault(z => z.UniqueId == invidiousChannel.AuthorId);
            var thumbnail = invidiousChannel.AuthorThumbnails?.Any(z => z.Height > 64) ?? false
                ? invidiousChannel.AuthorThumbnails.OrderBy(z => z.Height).First().Url
                : invidiousChannel.AuthorThumbnails?.OrderByDescending(z => z.Height).FirstOrDefault()?.Url;
            if (thumbnail != null && thumbnail.StartsWith("//"))
            {
                thumbnail = "https:" + thumbnail;
            }
            return new FoundChannel
            {
                ChannelId = existingChannel?.Id,
                ThumbnailUrl = thumbnail,

                Type = invidiousChannel.Type,
                ChannelHandle = invidiousChannel.ChannelHandle,
                Description = invidiousChannel.Description,
                DescriptionHtml = invidiousChannel.DescriptionHtml,
                Author = invidiousChannel.Author,
                AuthorId = invidiousChannel.AuthorId,
                AuthorUrl = invidiousChannel.AuthorUrl,
                AuthorThumbnails = invidiousChannel.AuthorThumbnails,
                AuthorVerified = invidiousChannel.AuthorVerified,
                AutoGenerated = invidiousChannel.AutoGenerated,
                SubCount = invidiousChannel.SubCount,
                VideoCount = existingChannel?.VideoCount ?? invidiousChannel.VideoCount,
            };
        });
        return response;
    }

    public async Task<IEnumerable<FoundAlgorithm>> SearchAlgorithms(string? username)
    {
        var algorithmsQuery = _videoDbContext.Algorithms.AsQueryable();
        if (!string.IsNullOrEmpty(username))
        {
            algorithmsQuery = algorithmsQuery.Where(z => z.Username == username);
        }
        var algorithms = await algorithmsQuery.ToListAsync();

        return algorithms.Select(z => new FoundAlgorithm
        {
            AlgorithmId = z.Id,
            AlgorithmName = z.Name,
            Description = z.Description,
            Username = z.Username
        });
    }

    private const int EST_VIDEO_COUNT = 100;

    public async Task<LoadAlgorithmResult> GetAlgorithm(int algorithmId)
    {
        var algorithmEntity = _videoDbContext.Algorithms.FirstOrDefault(z => z.Id == algorithmId);
        if (algorithmEntity == null)
        {
            throw new WebRequestException(400, $"algorithmId {algorithmId} not found");
        }
        var itemInfos = await _videoDbContext.GetAlgorithmItemInfos().Where(z => z.AlgorithmId == algorithmId).ToListAsync();
        var sumWeight = itemInfos.Sum(z =>
        {
            return z.ChannelCount.HasValue
                ? z.ChannelCount.Value * Math.Min(z.MaxChannelWeight, EST_VIDEO_COUNT) * Math.Max(z.WeightMultiplier, 0)
                : Math.Min(z.MaxChannelWeight, z.VideoCount ?? EST_VIDEO_COUNT) * Math.Max(z.WeightMultiplier, 0);
        });
        var result = new LoadAlgorithmResult
        {
            AlgorithmId = algorithmId,
            AlgorithmItems = itemInfos.Select(z => new LoadAlgorithmItem
            {
                ChannelGroupId = z.ChannelGroupId,
                ChannelId = z.ChannelId,
                MaxChannelWeight = z.MaxChannelWeight,
                WeightMultiplier = z.WeightMultiplier,
                Name = z.Name,
                VideoCount = z.VideoCount,
                FailureCount = z.FailureCount,
                EstimatedWeight = z.ChannelCount.HasValue
                    ? z.ChannelCount.Value * Math.Min(z.MaxChannelWeight, EST_VIDEO_COUNT) * Math.Max(z.WeightMultiplier, 0)
                    : Math.Min(z.MaxChannelWeight, z.VideoCount ?? EST_VIDEO_COUNT) * Math.Max(z.WeightMultiplier, 0)
            }),
            Description = algorithmEntity.Description,
            AlgorithmName = algorithmEntity.Name,
            Username = algorithmEntity.Username,
            EstimatedSumWeight = sumWeight,
        };
        return result;
    }

    public async Task<int> UpdateAlgorithm(UpdateAlgorithmRequest request, string username)
    {
        if (!request.Name.All(char.IsLetterOrDigit))
        {
            throw new WebRequestException(400, "Algorithm name must be alphanumeric");
        }
        var just1NonNull = request.AlgorithmItems.All(item => new object?[] { item.ChannelId, item.ChannelGroupId, item.NewChannel }.Count(p => p != null) == 1);
        if (!just1NonNull)
        {
            throw new WebRequestException(400, "each algorithmItem should have precisely 1 of the 3 nullable properties be non-null");
        }
        var newChannels = request.AlgorithmItems.Where(z => z.NewChannel != null).Select(z => z.NewChannel!);
        var newUniqueIds = newChannels.Select(z => z.AuthorId).ToList();
        if (newUniqueIds.Count() != newUniqueIds.Distinct().Count())
        {
            throw new WebRequestException(400, "NewChannels contains duplicates");
        }
        var algorithm = request.AlgorithmId.HasValue
            ? _videoDbContext.Algorithms.Include(z => z.AlgorithmItems).First(z => z.Id == request.AlgorithmId)
            : new AlgorithmEntity()
            {
                Name = request.Name,
                Username = username,
            };
        if (algorithm.Username != username)
        {
            throw new WebRequestException(400, "Algorithm belongs to a different user");
        }
        if (!request.AlgorithmId.HasValue || algorithm.Name?.ToLower() != request.Name.ToLower())
        {
            var nameConflicts = _videoDbContext.Algorithms.Where(z => z.Name == request.Name && z.Username == username).Any();
            if (nameConflicts)
            {
                throw new WebRequestException(400, $"user {username} already has an Algorithm named {request.Name}");
            }
        }
        var newChannelEntities = new List<ChannelEntity>();
        if (newChannels.Any())
        {
            //save all new channels to the database
            newChannelEntities = newChannels.Select(newChannel =>
            {
                var thumbnailsJson = System.Text.Json.JsonSerializer.Serialize(newChannel.AuthorThumbnails);
                return new ChannelEntity
                {
                    Name = newChannel!.Author,
                    UniqueId = newChannel!.AuthorId,
                    Handle = newChannel.ChannelHandle,

                    Description = newChannel.Description,
                    AuthorUrl = newChannel.AuthorUrl,
                    ThumbnailsJson = thumbnailsJson,
                    AuthorVerified = newChannel.AuthorVerified,
                    AutoGenerated = newChannel.AutoGenerated,
                    SubCount = newChannel.SubCount,
                    VideoCount = newChannel.VideoCount,

                    DateLastScraped = null,
                    ScrapedToOldest = false,
                    ScrapeFailureCount = 0
                };
            }).ToList();
            _videoDbContext.Channels.AddRange(newChannelEntities);
            _videoDbContext.SaveChanges();//this should assign Ids to newChannelEntities
            await _meilisearchAccess.AddChannels(newChannelEntities.Select(z => new ChannelMeilisearch
            {
                Id = z.Id,
                Id2 = z.Id,
                Handle = z.Handle,
                Name = z.Name,
                Description = z.Description
            }));
            var scheduler = await _schedulerFactory.GetScheduler();
            await scheduler.TriggerJob(JobKey.Create(nameof(VideoFetchJob)));
        }

        if (!request.AlgorithmId.HasValue)
        {
            _videoDbContext.Algorithms.Add(algorithm);
        }
        algorithm.Name = request.Name;
        algorithm.Description = request.Description;

        //remove all algorithmItems not found among request.AlgorithmItems
        var includedChannelIds = request.AlgorithmItems.Where(z => z.ChannelId.HasValue).Select(z => z.ChannelId).Distinct().ToList();
        var includedChannelGroupIds = request.AlgorithmItems.Where(z => z.ChannelGroupId.HasValue).Select(z => z.ChannelGroupId).ToList();
        if (algorithm.AlgorithmItems != null)
        {
            algorithm.AlgorithmItems = algorithm.AlgorithmItems
                .Where(z => includedChannelGroupIds.Contains(z.ChannelGroupId) || includedChannelIds.Contains(z.ChannelId))
                .ToList();
        }
        else
        {
            algorithm.AlgorithmItems = new List<AlgorithmItemEntity>();
        }

        //now start adding the new items
        //first add the newChannels
        var newChannelAlgorithmItems = request.AlgorithmItems.Where(z => z.NewChannel != null).Select(algorithmItem =>
        {
            var channelEntity = newChannelEntities.First(z => z.UniqueId == algorithmItem.NewChannel!.AuthorId);
            return new AlgorithmItemEntity
            {
                ChannelId = channelEntity.Id,
                MaxChannelWeight = algorithmItem.MaxChannelWeight,
                WeightMultiplier = algorithmItem.WeightMultiplier,
            };
        }).ToList();
        //then add the channelIds
        newChannelAlgorithmItems.AddRange(request.AlgorithmItems
            .Where(z => z.ChannelId.HasValue && !algorithm.AlgorithmItems.Any(zz => zz.ChannelId == z.ChannelId))
            .Select(z => new AlgorithmItemEntity
            {
                ChannelId = z.ChannelId,
                ChannelGroupId = z.ChannelGroupId,
                MaxChannelWeight = z.MaxChannelWeight,
                WeightMultiplier = z.WeightMultiplier,
            }));
        foreach (var newItem in newChannelAlgorithmItems)
        {
            algorithm.AlgorithmItems.Add(newItem);
        }
        _videoDbContext.SaveChanges();
        _globalCache.HandleAlgorithmUpdated(algorithm.Id);
        return algorithm.Id;
    }

    public void DeleteAlgorithm(int algorithmId, string username)
    {
        var algorithm = _videoDbContext.Algorithms.Include(z => z.AlgorithmItems).First(z => z.Id == algorithmId);
        if (algorithm.Username != username)
        {
            throw new WebRequestException(400, "Algorithm belongs to a different user");
        }
        _videoDbContext.Remove(algorithm);
        _videoDbContext.SaveChanges();
    }
}
