CREATE TABLE Video (
	Id INT PRIMARY KEY IDENTITY(1,1),
	ChannelId INT NOT NULL FOREIGN KEY REFERENCES Channel(Id),
	Title VARCHAR(100) NOT NULL,
	UniqueId VARCHAR(15) NOT NULL,

	Author VARCHAR(100) NULL,
	AuthorId VARCHAR(100) NULL,
	AuthorUrl VARCHAR(100) NULL,
	AuthorVerified BIT NOT NULL,

	ThumbnailsJson VARCHAR(MAX) NOT NULL,
	[Description] VARCHAR(1000) NOT NULL,
	DescriptionHTML VARCHAR(1000) NOT NULL,

	ViewCount BIGINT NOT NULL,
	ViewCountText VARCHAR(30) NULL,
	LengthSeconds INT NOT NULL,

	Published BIGINT NOT NULL,
	PublishedText VARCHAR(30) NULL,
	PremiereTimestamp INT NULL,
	LiveNow BIT NOT NULL,
	Premium BIT NOT NULL,
	IsUpcoming BIT NOT NULL,
	
	InsertDate DATETIME NOT NULL DEFAULT GETDATE(),
)