version: '3.9'

services:

  db: #this server as the database for both 
    image: joshtxdev/myvidious-postgres
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
# I also use adminer, which provides a web UI for browsing my database data/schema. 
  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
    restart: unless-stopped
    volumes:
      - meilisearchdata:/meili_data
    environment:
      MEILI_MASTER_KEY: password2
  invidious: 
    #runs on port 3000
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: postgres
          password: password
          host: db
          port: 5432
        check_tables: true
        external_port: 3000
        hmac_key: "rAndomstring"
    depends_on:
      - db
volumes:
  postgresdata:
  meilisearchdata: